### PR TITLE
spectrogram final edits

### PR DESCRIPTION
**Pull request by giannamoth**
Screen Shot 2022-02-02 at 15 57 06

@markus, I'Ve let for the moment the card about the PRO setting. SHeel I keep it or remove it and let just the 3 buttons one?
FOr the rest it is ok?

@vagechirkov  I'Ve changed the logic (again, sry about it xD) of the upload button. DOes it still work or it is not ok now?

Danke :)

### CODE REVIEW

**Comment by giannamoth** [comment]
This evening I'm going to adit the generating waveform page.

**Comment by vagechirkov** [comment]
Hey, @giannamoth, I will check it later today

**Comment by vagechirkov** [comment]
@giannamoth I have deleted the scripts from the previous PR

**Comment by vagechirkov** [comment]
> Screen Shot 2022-02-02 at 15 57 06
> 
> @markus, I'Ve let for the moment the card about the PRO setting. SHeel I keep it or remove it and let just the 3 buttons one? FOr the rest it is ok?
> 
> @vagechirkov I'Ve changed the logic (again, sry about it xD) of the upload button. DOes it still work or it is not ok now?
> 
> Danke :)

I think everything works fine!

**Comment by giannamoth** [comment]
image


@vagechirkov  check out the restyled spectrogram page. DO you think we can make it functioning by tomorrow evening?
(also the issue of the disappearing spectrogram is gone)

**Comment by vagechirkov** [comment]
> image
> 
> @vagechirkov check out the restyled spectrogram page. DO you think we can make it functioning by tomorrow evening? (also the issue of the disappearing spectrogram is gone)

I will commit in 10 minutes :)

**Comment by giannamoth** [comment]
nice :D I've also fixed the responsiveness of it.

**Comment by vagechirkov** [comment]
@giannamoth  I will connect it to the server, I need another 15 minutes

**Comment by markus** [comment]
You guys are tagging the wrong markus. No problem. I'll unsubscribe now.

**Comment by vagechirkov** [comment]
@giannamoth please try with the original `app.js` file. Everything should work now

**Comment by vagechirkov** [comment]
@giannamoth 

Three steps:

<details>

image
image
image

</details>

**Comment by giannamoth** [comment]
image


what shell I choose?

**Comment by giannamoth** [comment]
"use modified file from giannaDevelop" or "do not include this file on origin/giannaDevelop"

**Comment by vagechirkov** [comment]
> "use modified file from giannaDevelop" or "do not include this file on origin/giannaDevelop"

"use modified file from giannaDevelop" if think to have the latest version :)

**Comment by vagechirkov** [comment]
I think there is no need to create a separate results page since we have all the results on the spectrogram page!

**Comment by giannamoth** [comment]
ok! I have an error in the spectrogram page

**Comment by vagechirkov** [comment]
There are two small problems that I spotted: too long filename and the background dark line at the bottom of the screen.

<details>

image

</details>

**Comment by vagechirkov** [comment]
> ok! I have an error in the spectrogram page

What does it say?

**Comment by giannamoth** [comment]
I'm gonna fix those tomorrow morning :)

**Comment by giannamoth** [comment]
or never mind, I do it now! is the spectrogram apge working for you?

**Comment by vagechirkov** [comment]
> or never mind, I do it now! is the spectrogram apge working for you?

I think so

<details>

image


</details>

**Comment by giannamoth** [comment]
What happened to the turning wheel, and the text??

**Comment by giannamoth** [comment]
btw lines are shorter and background is fixed

**Comment by vagechirkov** [comment]
> btw lines are shorter and background is fixed

They should disappear after results generation is finished

**Comment by giannamoth** [comment]
achso! wait I'Ve read it wrong xD damn too tired I'm awake from 6 am. OK, can you explain me whatthe issue with the file name lenght?

And anyhow,I really have to go now :( I'm going to read ever<thign tomorrow morning and fix it

**Comment by vagechirkov** [comment]
> achso! wait I'Ve read it wrong xD damn too tired I'm awake from 6 am. OK, can you explain me whatthe issue with the file name lenght?
> 
> And anyhow,I really have to go now :( I'm going to read ever<thign tomorrow morning and fix it

image

**Comment by vagechirkov** [comment]
@giannamoth I deployed it, you can check how it looks like on the server: https://noise-enricher.herokuapp.com/

**Comment by vagechirkov** [comment]
This is how it looks on the Heroku now:

<details>

image

image

image


image


</details>


I think there are some minor changes related to the spectrograms and this is it! I really like it!

**Comment by giannamoth** [comment]
OK I get about the file name now!
About the spectrogram, it is veeery different from the UX vision now :
- The spinning wheels should stay within the in-coming and the new-coming spectrogram and disappear after the new one is generated
-  Upper thext and lower text has disappeared now :/


Is it ok if I add those things? :)

**Comment by giannamoth** [comment]
Or bar is fixed , and I have his issue with the spectrogram:
Screen Shot 2022-02-03 at 09 11 54

How can I remove the white part again? I’m lookign at the documentation and I don’T find it

**Comment by giannamoth** [comment]
OOOOOkei :) Endlisch is here :) I've messed up with the link paths in other to have the thing working. 

here and here:
Screen Shot 2022-02-03 at 10 53 25


Screen Shot 2022-02-03 at 10 52 56

I don't remember how they where 😢  Can you check them @vagechirkov ? :)

**Comment by giannamoth** [comment]
When you are ready fell free to Merge this pull request ;)

**Comment by vagechirkov** [comment]
@giannamoth alright! There is a delay before the spectrogram appears, do you think it is easy to fix?

**Comment by giannamoth** [comment]
hum...not sure 🤔  what if I'll solve it in the weekend for the final delivery? I have to work (office work, not fun doing work xD) now 😢

**Comment by vagechirkov** [comment]
> hum...not sure 🤔 what if I'll solve it in the weekend for the final delivery? I have to work (office work, not fun doing work xD) now 😢

sure, no problems! I will merge this PR in the next 10 minutes

**Pull request merged**
