### PR TITLE
Templating routing

### PR DESCRIPTION
**Pull request by vagechirkov**
I introduced the basic [ejs teplates](https://ejs.co/) and routes. This update is necessary to include backend-related functionality in the web application. As for routes, now, when a user presses the "Generate track" button, the spectrogram page opens, and then after there is a response from AI, the result page opens (this step is not implemented yet).

I have deployed this update on Heroku to simplify reviewing: https://noise-enricher.herokuapp.com/

To run the code on the local computer, you would need to type the following commands in the terminal (after cloning the code from the pull request):

```bash

cd node_app/server/
npm init
nodemon app.js

```

Then you should be able to open the application in your web browser: `http://127.0.0.1:3030/`

@giannamoth I have broken some of the styles, but I have tried to change frontend-related code as little as possible. Please, let me know what do you think about the templates.

### CODE REVIEW

**Comment by giannamoth** [comment]
Hei Valeri :)
I'm not death just a crazy time at work :/ gonna review this after work this afternoon!

Sry for the delay 🙏

**Comment by vagechirkov** [comment]
> Hei Valeri :)
> I'm not death just a crazy time at work :/ gonna review this after work this afternoon!
> 
> Sry for the delay 🙏 

No worries, I am still working on backend related stuff:)

**Comment by giannamoth** [comment]
Hola Valeri, how can I check the changes before to merge it with my local machine?

I was usually doing it without effort and this evening I don't find the way 🙈

**Comment by vagechirkov** [comment]
> Hola Valeri, how can I check the changes before to merge it with my local machine?
> 
> I was usually doing it without effort and this evening I don't find the way 🙈

Yeah, it needs some effort, but there is the only way, unfortunately. Did the comment in the first message in this PR help?

**Comment by giannamoth** [comment]
about page is out of work :(

**Pull request merged**
