### PR TITLE
Embrace the noise

### PR DESCRIPTION
**Pull request by vagechirkov**
Finally, generating audios!

### CODE REVIEW

**Comment by vagechirkov** [comment]
I don't know how to decrease the size of dependencies further, so I cannot deploy it. @christian-eismann any ideas?

image

image

image

**Comment by christian-eismann** [comment]
Thank you Valerii! Can you provide a list of all dependencies, or is the
installing procedure done automatically? in the worst case, we have to
substitute the classification with a dummy so we can save about 200MB.

Valerii ***@***.***> schrieb am Do., 27. Jan. 2022, 04:28:

**Review by christian-eismann — APPROVED** [review]
Looks fine to me! Thank you Valerii!

**Comment by vagechirkov** [comment]
@christian-eismann all the dependencies that I installed are in the requirements.txt (see changed files):

```

-f https://download.pytorch.org/whl/torch_stable.html
matplotlib==3.5.0
numpy==1.21.4
torchaudio==0.10.0+cpu
tensorflow-cpu==2.7.0
torch==1.10.0+cpu
torchaudio==0.10.0+cpu
librosa==0.8.1
AudioSegment==0.23.0
pydub==0.25.1
h5py==2.10.0

```

Do you think we can somehow exclude `torch` because it takes about 200Mb of the slug size? At least for now, to test the audio generator deployent on Heroku.

**Comment by RoitRapha** [comment]
@vagechirkov torch is just used for the classifier, not for the vae generator, so I think for trying that out, you can delete that.
But i think you also need to install pickle (pickle5) and I am not sure if you maybe need also keras. Is everything we need included in tensorflow itself? Because on my computer i just installed keras, then tensorflow comes together with it. Do you know that @christian-eismann?

**Comment by vagechirkov** [comment]
> @vagechirkov torch is just used for the classifier, not for the vae generator, so I think for trying that out, you can delete that. But i think you also need to install pickle (pickle5) and I am not sure if you maybe need also keras. Is everything we need included in tensorflow itself? Because on my computer i just installed keras, then tensorflow comes together with it. Do you know that @christian-eismann?

Okey dokey, I will try to delete `torch` and  deploy the app again in this PR. Thank you!

**Comment by christian-eismann** [comment]
yes, just comment out the sections that use torch. torchaudio is also not needed. maybe you have to comment out the definition self.to_classifier() in input_preprocessing.py. otherwise it could display an error if you initialize the class preprocessor.

**Comment by vagechirkov** [comment]
462/500!! Now I have other errors but I will fix this

image

**Comment by vagechirkov** [comment]
AAAAAAAAAA it is working!!!!!! We are online!

@christian-eismann @RoitRapha  @giannamoth 

you can try to upload `.wav` file. It takes 5-10 seconds before opening the results 

https://noise-enricher.herokuapp.com/generate

**Comment by RoitRapha** [comment]
Awesome !!!!! I will try in a bit :)

**Comment by RoitRapha** [comment]
@vagechirkov how should it work? I chose a wav file of my computer and then pressed "generate new track". The page reloads but nothing happens. What did I do wrong?

**Comment by vagechirkov** [comment]
> @vagechirkov how should it work? I chose a wav file of my computer and then pressed "generate new track". The page reloads but nothing happens. What did I do wrong?

could you try this file? https://github.com/TechLabs-Berlin/wt21-the-noise-enricher/blob/develop/python_app/piano_16000_mono.wav

**Comment by vagechirkov** [comment]
The page reloads if there is an error in python. If something goes wrong, I open the home page

**Comment by christian-eismann** [comment]
Same issue here: 
The piano file is working, other files not. Maybe the issue is the follwing: the piano file is 16KHz, my other testfiles are 22KHz

**Comment by christian-eismann** [comment]
However: really cool!

**Comment by RoitRapha** [comment]
> > @vagechirkov how should it work? I chose a wav file of my computer and then pressed "generate new track". The page reloads but nothing happens. What did I do wrong?
> 
> could you try this file? https://github.com/TechLabs-Berlin/wt21-the-noise-enricher/blob/develop/python_app/piano_16000_mono.wav

this works :) i just choose a 3 second junk of some training data of mine

**Comment by vagechirkov** [comment]
> Same issue here: The piano file is working, other files not. Maybe the issue is the follwing: the piano file is 16KHz, my other testfiles are 22KHz

Here is the error description from heroku

<details>

```bash

2022-01-27T11:06:04.247924+00:00 app[web.1]: POST /generate 302 336.784 ms - 76
2022-01-27T11:06:05.462047+00:00 app[web.1]: stderr chunk: /app/.heroku/python/lib/python3.8/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
2022-01-27T11:06:05.462053+00:00 app[web.1]: warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2022-01-27T11:06:05.462053+00:00 app[web.1]: 
2022-01-27T11:06:07.120252+00:00 app[web.1]: stderr chunk: WARNING:tensorflow:From /app/.heroku/python/lib/python3.8/site-packages/keras/layers/normalization/batch_normalization.py:532: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
2022-01-27T11:06:07.120256+00:00 app[web.1]: Instructions for updating:
2022-01-27T11:06:07.120257+00:00 app[web.1]: Colocations handled automatically by placer.
2022-01-27T11:06:07.120258+00:00 app[web.1]: 
2022-01-27T11:06:08.310607+00:00 app[web.1]: stderr chunk: 2022-01-27 11:06:08.310262: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
2022-01-27T11:06:08.310617+00:00 app[web.1]: To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-27T11:06:08.310618+00:00 app[web.1]: 
2022-01-27T11:06:08.802849+00:00 app[web.1]: stderr chunk: /app/.heroku/python/lib/python3.8/site-packages/keras/engine/training_v1.py:2079: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
2022-01-27T11:06:08.802874+00:00 app[web.1]: updates=self.state_updates,
2022-01-27T11:06:08.802875+00:00 app[web.1]: 
2022-01-27T11:06:08.805223+00:00 app[web.1]: stderr chunk: Traceback (most recent call last):
2022-01-27T11:06:08.805224+00:00 app[web.1]: File "/app/python_app/call_generate_audio.py", line 11, in <module>
2022-01-27T11:06:08.805225+00:00 app[web.1]: 
2022-01-27T11:06:08.805314+00:00 app[web.1]: stderr chunk:     create_sound(input_arrays, minmax, sys.argv[2], sys.argv[3])
2022-01-27T11:06:08.805314+00:00 app[web.1]: File "/app/python_app/sound_generator.py", line 13, in create_sound
2022-01-27T11:06:08.805315+00:00 app[web.1]: 
2022-01-27T11:06:08.805393+00:00 app[web.1]: stderr chunk:     generated, latent = model.reconstruct(input_array)
2022-01-27T11:06:08.805393+00:00 app[web.1]: 
2022-01-27T11:06:08.805455+00:00 app[web.1]: stderr chunk:   File "/app/python_app/enricher_models.py", line 105, in reconstruct
2022-01-27T11:06:08.805455+00:00 app[web.1]: 
2022-01-27T11:06:08.805992+00:00 app[web.1]: stderr chunk:     latent_representations = self.encoder.predict(images[:, :, :, :])
2022-01-27T11:06:08.805993+00:00 app[web.1]: 
2022-01-27T11:06:08.806050+00:00 app[web.1]: stderr chunk:   File "/app/.heroku/python/lib/python3.8/site-packages/keras/engine/training_v1.py", line 970, in predict
2022-01-27T11:06:08.806050+00:00 app[web.1]: 
2022-01-27T11:06:08.806418+00:00 app[web.1]: stderr chunk:     return func.predict(
2022-01-27T11:06:08.806419+00:00 app[web.1]: 
2022-01-27T11:06:08.806475+00:00 app[web.1]: stderr chunk:   File "/app/.heroku/python/lib/python3.8/site-packages/keras/engine/training_arrays_v1.py", line 699, in predict
2022-01-27T11:06:08.806475+00:00 app[web.1]: 
2022-01-27T11:06:08.806738+00:00 app[web.1]: stderr chunk:     return predict_loop(
2022-01-27T11:06:08.806738+00:00 app[web.1]: 
2022-01-27T11:06:08.806824+00:00 app[web.1]: stderr chunk:   File "/app/.heroku/python/lib/python3.8/site-packages/keras/engine/training_arrays_v1.py", line 392, in model_iteration
2022-01-27T11:06:08.806824+00:00 app[web.1]: 
2022-01-27T11:06:08.807007+00:00 app[web.1]: stderr chunk:     aggregator.finalize()
2022-01-27T11:06:08.807008+00:00 app[web.1]: 
2022-01-27T11:06:08.807064+00:00 app[web.1]: stderr chunk:   File "/app/.heroku/python/lib/python3.8/site-packages/keras/engine/training_utils_v1.py", line 443, in finalize
2022-01-27T11:06:08.807065+00:00 app[web.1]: 
2022-01-27T11:06:08.807234+00:00 app[web.1]: stderr chunk:     self.results = tf.nest.pack_sequence_as(self._structure, self.results)
2022-01-27T11:06:08.807234+00:00 app[web.1]: 
2022-01-27T11:06:08.807301+00:00 app[web.1]: stderr chunk:   File "/app/.heroku/python/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 757, in pack_sequence_as
2022-01-27T11:06:08.807301+00:00 app[web.1]: 
2022-01-27T11:06:08.807599+00:00 app[web.1]: stderr chunk:     return _pack_sequence_as(structure, flat_sequence, expand_composites)
2022-01-27T11:06:08.807599+00:00 app[web.1]: 
2022-01-27T11:06:08.807658+00:00 app[web.1]: stderr chunk:   File "/app/.heroku/python/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 623, in _pack_sequence_as
2022-01-27T11:06:08.807659+00:00 app[web.1]: 
2022-01-27T11:06:08.807868+00:00 app[web.1]: stderr chunk:     raise ValueError(
2022-01-27T11:06:08.807869+00:00 app[web.1]: 
2022-01-27T11:06:08.807922+00:00 app[web.1]: stderr chunk: ValueError: The target structure is of type `<class 'NoneType'>`
2022-01-27T11:06:08.807923+00:00 app[web.1]: None
2022-01-27T11:06:08.807923+00:00 app[web.1]: However the input structure is a sequence (<class 'list'>) of length 0.
2022-01-27T11:06:08.807924+00:00 app[web.1]: []
2022-01-27T11:06:08.807924+00:00 app[web.1]: nest cannot guarantee that it is safe to map one to the other.
2022-01-27T11:06:08.807924+00:00 app[web.1]: 


```




</details>

**Comment by vagechirkov** [comment]
I think something is wrong with `self.encoder.predict(images[:, :, :, :])` dimensions, but I am not sure

**Comment by vagechirkov** [comment]
I would suggest I merge this PR, and then we can open the new one to fix this error

**Comment by christian-eismann** [comment]
@vagechirkov @RoitRapha i think i figured it out: the problem is, that out both test files are exactly 3 seconds long. this could result to an error looping through one of the lists or dictionaries. tried out with longer wav files, it worked!

**Comment by vagechirkov** [comment]
**But we are officially enhancing noise now!!!**

**Comment by vagechirkov** [comment]
> @vagechirkov @RoitRapha i think i figured it out: the problem is, that out both test files are exactly 3 seconds long. this could result to an error looping through one of the lists or dictionaries. tried out with longer wav files, it worked!

Yeah, by the way, are you planning to bind the reconstructed chunks back to the normal file? Right now I show only the first chunk

**Comment by vagechirkov** [comment]
I merge this PR, it fulfilled its purpose :)

**Comment by christian-eismann** [comment]
> > @vagechirkov @RoitRapha i think i figured it out: the problem is, that out both test files are exactly 3 seconds long. this could result to an error looping through one of the lists or dictionaries. tried out with longer wav files, it worked!
> 
> Yeah, by the way, are you planning to bind the reconstructed chunks back to the normal file? Right now I show only the first chunk

yes, i will, but i cant work on the code currently

**Comment by RoitRapha** [comment]
> 

Yes, this is the plan. But I think we will discuss this later in the ai team meeting :)
Also so far it is not really enriching the noise :D

**Comment by vagechirkov** [comment]
> > > @vagechirkov @RoitRapha i think i figured it out: the problem is, that out both test files are exactly 3 seconds long. this could result to an error looping through one of the lists or dictionaries. tried out with longer wav files, it worked!
> > 
> > 
> > Yeah, by the way, are you planning to bind the reconstructed chunks back to the normal file? Right now I show only the first chunk
> 
> yes, i will, but i cant work on the code currently

No problems, we have plenty of time to figure out these things before the deadline!

**Pull request merged**
