### PR TITLE
new Landing page

### LINKED ISSUE #42: Selecting different sound styles for autoencoder
- add 'genre'-parameter to VAE class in enricher_models.py
- pass the genre parameter from create_sound.py file
- store all weights and parameters with "_genre" in filename in the folder python_app/models

### PR DESCRIPTION
**Pull request by giannamoth**
Updated landing page.

Customization of upload button and results samples are still missing (next on my list)

@vagechirkov che if like this can still work from a back end pov the radio-box

### CODE REVIEW

**Comment by vagechirkov** [comment]
The main page looks great!

image

But something happened with the pro page

image

**Comment by giannamoth** [comment]
Upsi!` Pro page` and finalization of `landing page` are on my today list 😎

**Comment by giannamoth** [comment]
It should be fixed now :)

**Comment by giannamoth** [comment]
Later this evenig (hopefully ready before our call) I'm gonna finalize the index.js page 😎

**Pull request merged**
