### PR TITLE
add alert message if file is too big

### LINKED ISSUE #49: Add uploaded audio file check

### PR DESCRIPTION
**Pull request by vagechirkov**
Show alert message if an audio file is too big. 

@giannamoth could you please check what is wrong with the bootstrap styles (see more info [here](https://getbootstrap.com/docs/4.0/components/alerts/))? I am using them in the `flash.ejs`.

Everything looks fine, but the close button doesn't work:

image

#45

### CODE REVIEW

**Comment by giannamoth** [comment]
I'm checking right now :)

**Comment by giannamoth** [comment]
I really have no clue :(

**Comment by vagechirkov** [comment]
I found the error, it was because of the jquery version!

**Comment by giannamoth** [comment]
nice :D happy to hear that :)

**Comment by vagechirkov** [comment]
But the ugly close button is still here :)

image

**Comment by giannamoth** [comment]
I was actually also trying the other day to use a symbol in the alert, and was not loading it 🤔

**Comment by vagechirkov** [comment]
Fixed :)

image


It was the wrong button class name. [Here](https://getbootstrap.com/docs/5.0/components/close-button/) is the correct class.

**Comment by vagechirkov** [comment]
@giannamoth, let me know if I can merge it! The only problem left is this hack in `flash.ejs`:

```ejs

<div class="flash-message" style="padding-top: 3em;">

```

**Comment by giannamoth** [comment]
you can merge it!

**Pull request merged**
