### PR TITLE
add team links

### PR DESCRIPTION
**Pull request by vagechirkov**
Feel free to update this PR or paste the link for your profile as a comment

### CODE REVIEW

**Comment by christian-eismann** [comment]
https://www.linkedin.com/in/christian-eismann-a9a01719a

thank you Valerii!

**Comment by marcospozzo** [comment]
https://github.com/marcospozzo/

Thanks Valerii!

**Comment by RoitRapha** [comment]
https://www.linkedin.com/in/raphael-wallsberger-0698a01b9/

thanks buddy :)

**Comment by giannamoth** [comment]
https://github.com/giannamoth
https://www.linkedin.com/in/gianna-moscoso-thompson-7a1677a3/

danke danke :)(I've forgotten the linkedin one 🙏 @vagechirkov )

**Comment by vasenina** [comment]
https://github.com/vasenina

https://www.linkedin.com/in/yulia-vasenina


Thank you)

**Comment by RoitRapha** [comment]
if we add all, here is my github :D :
https://github.com/RoitRapha

**Pull request merged**
