### PR TITLE
Polishing of code and added explanation text

### PR DESCRIPTION
**Pull request by giannamoth**
Hei Valerii, I've added the text we have mentioned on the about page and the goPRO one.

I wanted to work also on the Spectrogram page but (again) I was not able to make it work :/

I've changed the text in the app.js and in the spectrogram.js..... what did I miss? :/

Anyhow, please check if I've messed up with the code. I think I didn't, just to be sure :)

### CODE REVIEW

**Review by vagechirkov — APPROVED** [review]
Looks good to me! Thank you! I have deployed this version https://noise-enricher.herokuapp.com/

**Comment by vagechirkov** [comment]
@giannamoth regarding the `spectrogram.ejs` testing now the logic is slightly different. To test you need to update `app.js`, as you did it before, and replace `spectrogram.ejs` with the following code:

<details>

```ejs

<% layout('layouts/boilerplate.ejs') %>
    <link rel="stylesheet" href="../../public/css/spectrogram.css">
    <%- include("../partials/background_animation.ejs") %>

        <div class="canvas">

            <div id="results">
                <h2 id="waitingTitle">Results will appear in 5 to 30 seconds...</h2>
            </div>

            <div class="spectrogram">
                <section id="spectrogram-input">
                    <h5>Your input sound file spectrogram</h5>
                    <div id="incomingWaveform"><span id="incomingSpectrogram"></span></div> 
                      
                    <p><audio src="../../public/uploads/someaudio.wav" type="audio/wav" controls loop></audio> </p>
                </section>
                <section id="spectrogram-loading">
                    <img id="spectrogram-loading-gif" src="../../content/loading.gif" alt="loading wheel">
                </section>
                <section id="spectrogram-output">
                    <h5>Output sound file spectrogram</h5>
                    <div id="resultWaveform"><span id="resultSpectrogram"></span></div>
                    <p><audio src="../../public/uploads/someaudio.wav" type="audio/wav" id="outputAudio" controls loop></audio> </p>
                </section>
            </div>

            <h2 id="thankyou">Thank you for using the noise enricher!</h2>
            <div id="thx">
                <p>How did it go? </p>
                <span><img src="../../content/thumb-up.png"><img src="../../content/thumb-down.png"></span>
            </div>
            <a href="/">Generate a new track here</a>
      

        </div>

        <script src="https://unpkg.com/wavesurfer.js"></script>
        <script src="https://unpkg.com/wavesurfer.js@5.2.0/dist/plugin/wavesurfer.spectrogram.min.js"></script>
        <script src="../../public/js/draw_spectrogram.js"></script>
        <script>
            const wavesurfer = drawInputSpectrogram("../../public/uploads/someaudio.wav");
            const resultWavesurfer = drawOutputSpectrogram("../../public/uploads/someaudio.wav");

```

</details>


Note: `uploads` folder should have `someaudio.wav` file inside.

**Comment by giannamoth** [comment]
Hei Hie @vagechirkov  :) Is done, I've updated the tool :) Thake a look that the links are not broken :)

**Comment by vagechirkov** [comment]
@giannamoth Everything looks great! I've updated the deployment :)

**Comment by giannamoth** [comment]
Nice :D

Thank you :))

**Comment by vagechirkov** [comment]
@giannamoth should I merge this PR?

**Comment by giannamoth** [comment]
Oui :)

**Comment by giannamoth** [comment]
was a pleasure to work with you Valerii :D !!!!!

**Pull request merged**
