### PR TITLE
add different sound styles support

### LINKED ISSUE #42: Selecting different sound styles for autoencoder
- add 'genre'-parameter to VAE class in enricher_models.py
- pass the genre parameter from create_sound.py file
- store all weights and parameters with "_genre" in filename in the folder python_app/models

### PR DESCRIPTION
**Pull request by vagechirkov**
#42

More information about bootstrap buttons checkbox [here](https://getbootstrap.com/docs/3.4/javascript/#buttons-checkbox-radio).

### CODE REVIEW

**Comment by vagechirkov** [comment]
@giannamoth, could you check the button style?

image

**Comment by giannamoth** [comment]
Hei Valerii! I'm confused, I was waiting for the UX guys' input to build the buttons. + we don'T need anymore the STyle section. Actually, the `style section` is gonna become the new `blues`, `hip-hop`, `metal selection`.

Correct?

And depending on the style, I would build the button with bootstrap or with native HTML+CSS.

**Comment by giannamoth** [comment]
I hope is not a problem if I'm going to make them from scratch again.

**Comment by giannamoth** [comment]
seriously, I have mich more control without bootstrap than with

**Comment by vagechirkov** [comment]
@giannamoth sure! I believe these buttons should be radio buttons because the user should select only one option. In any case, this should not be a problem to adjust the input if needed. Let me know what do you think!

**Comment by giannamoth** [comment]
I'm having them as a radio, but built with HTML +CSS. I'm gonna make a pull request soon with that update

**Comment by vagechirkov** [comment]
> I'm having them as a radio, but built with HTML +CSS. I'm gonna make a pull request soon with that update

Ahh, of course, style should not affect the functionality! Should I merge this PR then?

**Comment by giannamoth** [comment]
actually, I'm completely changing the structure in the HTML file (no more 3 blocks but two, no Bootstrap for the radio).

SO I don't think is necessary to merge this, it is probably going to cause some merge conflicts

**Comment by giannamoth** [comment]
```
                <!-- 2 gray blocks -->
                <div id="allParams">
                    <section id="styleSection">
                        <div id="styleSelection">
                            <div>
                                <input type="radio" id="Blues" name="style" value="blues" checked>
                                <label for="Blues">Blues</label>
                            </div>

                            <div>
                                <input type="radio" id="Hiphop" name="style" value="hiphop">
                                <label for="Hiphop">Hiphop</label>
                            </div>

                            <div>
                                <input type="radio" id="Metal" name="style" value="metal">
                                <label for="Metal">Metal</label>
                            </div>
                        </div>
                        <p>Choose a style</p>
                    </section>

                    <section id="goProSection">
                        <p id="proText">
                            <img class="logoSVG" src="../content/logo.svg" alt="logo"><br>
                            <a href="/generate/pro">Use our <span>Pro version</span> with more settings</a>
                        </p>
                    </section>
                </div>

```

**Comment by giannamoth** [comment]
that is how it looks now

**Comment by giannamoth** [comment]
image

**Comment by vagechirkov** [comment]
Alright, I will undo the frontend part here and merge!

**Pull request merged**
