### PR TITLE
Ux updates, UI resources added

### PR DESCRIPTION
**Pull request by marcospozzo**
Screenshots addes, readme update, and figma file update. UI resources added.

### CODE REVIEW

**Comment by marcospozzo** [comment]
@vagechirkov if I merge this PR, will it join the big merge between develop and main? Or how do I to include this changes in the final delivery? Thanksss

**Comment by vagechirkov** [comment]
> @vagechirkov if I merge this PR, will it join the big merge between develop and main? Or how do I to include this changes in the final delivery? Thanksss

I will merge develop branch into the main again later today. No worries, all updates will be in the final delivery :)

**Comment by vagechirkov** [comment]
@marcospozzo @vasenina  Can I merge this PR?

**Comment by marcospozzo** [comment]
Yes, please! @vagechirkov

**Pull request merged**
